name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch: # Allows manual triggering

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

permissions:
  contents: read

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Log Into Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # During a release workflow the new git tag is provided and is automatically used by this step to generate the new image tags.
      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and Push Docker Image
        if: steps.meta.outputs.tags != ''
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  get-charts:
    name: Get Charts
    runs-on: ubuntu-latest
    needs: [build-and-push]
    outputs:
      changeset: ${{ steps.updater.outputs.changeset }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Update Helm Chart Versions
        uses: lrstanley/helm-version-updater@91c756dbbc1ac62747df7131c32b0fbc8788222f # v1.0.4
        id: updater
        with:
          check-dir: charts/
          dry-run: true

  helm-version-updater:
    name: Update Helm Chart Versions and Create a PR
    runs-on: ubuntu-latest
    needs: [get-charts]
    if: ${{ fromJSON(needs.get-charts.outputs.changeset).changes != null }}
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        change: ${{ fromJSON(needs.get-charts.outputs.changeset).changes }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm Chart Versions
        uses: lrstanley/helm-version-updater@91c756dbbc1ac62747df7131c32b0fbc8788222f # v1.0.4
        id: updater
        with:
          check-dir: ${{ matrix.change.path }}

      - name: Create PR
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          token: ${{ secrets.USER_PAT }}
          add-paths: "${{ matrix.change.chart.path }}"
          title: >-
            update chart ${{ matrix.change.chart.name }}
            from ${{ matrix.change.old_version }}
            to ${{ matrix.change.new_version }}
          commit-message: >-
            chore(${{ matrix.change.chart.name }}): update chart
            from ${{ matrix.change.old_version }}
            to ${{ matrix.change.new_version }}
          body: |
            Updating chart `${{ matrix.change.chart.name }}`:

            - Bumping **version** from `${{ matrix.change.old_version }}` to `${{ matrix.change.new_version }}`.
            - Bumping **appVersion** from `${{ matrix.change.old_app_version }}` to `${{ matrix.change.new_app_version }}`.

            Pull request auto-generated by [helm-version-updater](https://github.com/lrstanley/helm-version-updater).
          signoff: true
          branch: "chore/chart-version-updater/${{ matrix.change.chart.name }}"
          delete-branch: true
          base: main
          labels: "chore,chart,chart-${{ matrix.change.chart.name }}"
